* About

This file contains links and hints to remind how I configured my
desktop.

* Xmonad
** quake console
   Set up using Scratchpad module
   https://pbrisbin.com/posts/xmonad_scratchpad/. Note that Scratchpad
   changes window class of terminal (use mod+F1 to check). This means
   that terminals which use XResources-based configuration should be
   configured using another name. For example with urxvt scratch and
   non-scratch versions use URxvt and urxvt names.

** key codes
http://hackage.haskell.org/package/X11-1.6.0.2/docs/Graphics-X11-Types.html#g:2

* X configuration
** Xsessions

*** lightdm

lightdm login manager looks into /usr/share/xsessions/*.desktop
files. These files contain TryExec and Exec and commands which tells
which command to execute during session start.

*** init files

startx command uses ~/.xinitrc file.

lightdm command executes ~/.xsessionrc file.

*** Gnome sessions

Commands like gnome-session --session=gnome are configured by files in
/usr/share/gnome-session/*.session. Here you can configure which Gnome
parts are required by you session.

** Fonts, icons

There are programs like gnome-settings-daemon or xsettingsd which
reads configuration files and somehow changes appearance of other
X-programs. If you don't run settings daemon then X-server will read
settings from it's configuration files (some xml files in /etc/
folder) and pass them to X-programms. xrdb utility changes X-server
configuration using XResources file. There are also themes for gtk and
qt programs. Themes for gtk programs are described in ~/.gtkrc-2.0
file.

1. configure ~/.Xresources file and execute xrdb -merge
   .Xresources.

There are directory which contains system fonts settings /etc/fonts/conf.d/

#+begin_example
cd /etc/fonts/conf.d
sudo ln -s ../conf.avail/10-sub-pixel-rgb.conf .
#+end_example

*** Gtk
1. use lxappearence utility to configure ~/.gtkrc-2.0 file.
2. use gconf-editor to configure /desktop/gnome/interface/*-font-name

*** Qt

1. [[https://wiki.archlinux.org/index.php/Uniform_look_for_Qt_and_GTK_applications][Arch Wiki]]
  #+begin_example
  ~/.config/Trolltech.conf

  ...
  [Qt]
  style=GTK+
  ...
  #+end_example

  Or use qtconfig-qt4 utility from qt4-qtconfig package.

*** Firefox
Install addon Default Zoom Level. Then either in visual config or in
about:config change it's values.

*** Thunderbird

+ Install Themes and Fonts changer.
+ Use Zoom In (\C-=) and Zoom Out (\C--) to adjust reading pane zoom.

** Keyboard layout

There are many places which could control your keyboard layout. If you
don't use settings daemons then setxkbmap and xmodmap will work.

** Terminal and shell
*** Terminal
1. Install urxvt
2. Configure color theme
   https://wiki.mpich.org/mpich/index.php/Configure_xterm_Fonts_and_Colors_for_Your_Eyeball
3 Install addons
   http://funloop.org/post/2015-06-25-urxvt-plugins.html

   mkdir ~/.urxvt/ext
   git clone https://github.com/muennich/urxvt-perls --depth 1 ~/.urxvt/ext

4. Configure addons in ~/.Xresources

5. Configure colors

   Bonus: [[https://github.com/chriskempson/base16][base16]] - set of 16-color schemes for text editors and
   terminal emulators.

   [[http://www.xcolors.net/][A lot of X themes]]

   [[https://wiki.archlinux.org/index.php/X_resources#Terminal_colors][Here]] is description of *color0..15 meaning.

*** Shell
Most terminals (at least gnome-terminal, urxvt, and XTerm, for
example) that are started within a desktop environment such as Unity
will use the SHELL environment variable to select the shell when the
are launched.

**** Install fish shell
#+begin_example
echo "export SHELL=/usr/bin/fish" >> ~/.profile
chsh -s $(grep /fish$ /etc/shells | tail -1)
#+end_example

**** Install zsh (didn't migrated to zsh yet)

#+begin_example
sh -c "$(wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
git clone git://github.com/tarruda/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
git clone git://github.com/tarruda/zsh-autosuggestions zsh-autosuggestions
#+end_example

edit ~/.zshrc
plugins=(git emacs zsh-syntax-highlighting zsh-autosuggestions)


** Clipboard
There are 3 types of text shared between X-applications: "primary
selection", "secondary selection" and "clipboard". Use
xclip -i -selection clipboard
xclip -o -selection clipboard
To copy/paste to/from clipboard

* General system config
** Locale
Edit /etc/default/locale. Set either "ru_RU.UTF-8" or "en_US.UTF-8" to
each field.

** Notifications
https://github.com/knopwob/dunst
Configuratin file ~/.config/dunst/dunstrc

** Hibernate
sudo -H gedit /etc/systemd/logind.conf
HandlePowerKey=hibernate
** autokey
Fix for exclusion window filter https://groups.google.com/forum/#!topic/autokey-users/ZYrQLPveh4g
Edit /usr/lib/python2.7/dist-packages/autokey/model.py and remove or from  def _should_trigger_window_title(self, windowInfo):  function

* Applications
** DLNA media server
+ mediatomb

  You can find web-based interface address in logs
  #+begin_example
  cat /var/log/mediatomb.log | grep http://192 | tail -n 1 | cut -f 7 -d\
  #+end_example

+ minidlna

  * DLNA media server

** MTP
Checked several packages:
+ mtp-tools
+ mtpfs
+ jmtpfs

None of them detected my ASUS Phone.

** FTP
+ Install
  sudo apt-get install vsftpd

+ Enable anonymous users in /etc/vsftpd.conf
  anonymous_enable=Yes

+ Change home directory for anonymous user
  sudo usermod -d /mnt/ ftp
** Human language translators and dictionaries
*** dict

[[http://askubuntu.com/questions/380847/is-it-possible-to-translate-words-via-terminal][Stack Overflow post]]
#+begin_example
sudo apt-get install dictd
sudo apt-get install dict-freedict-eng-rus
#+end_example
