* About

This file contains links and hints to remind how I configured my
desktop.

* Xmonad
** quake console
   Set up using Scratchpad module
   https://pbrisbin.com/posts/xmonad_scratchpad/. Note that Scratchpad
   changes window class of terminal (use mod+F1 to check). This means
   that terminals which use XResources-based configuration should be
   configured using another name. For example with urxvt scratch and
   non-scratch versions use URxvt and urxvt names.

** key codes
http://hackage.haskell.org/package/X11-1.6.0.2/docs/Graphics-X11-Types.html#g:2

* X configuration
** Xsessions

*** lightdm

lightdm login manager looks into /usr/share/xsessions/*.desktop
files. These files contain TryExec and Exec and commands which tells
which command to execute during session start.

*** init files

startx command uses ~/.xinitrc file.

lightdm command executes ~/.xsessionrc file.

*** Gnome sessions

Commands like gnome-session --session=gnome are configured by files in
/usr/share/gnome-session/*.session. Here you can configure which Gnome
parts are required by you session.

** Fonts, icons

There are programs like gnome-settings-daemon or xsettingsd which
reads configuration files and somehow changes appearance of other
X-programs. If you don't run settings daemon then X-server will read
settings from it's configuration files (some xml files in /etc/
folder) and pass them to X-programms. xrdb utility changes X-server
configuration using XResources file. There are also themes for gtk and
qt programs. Themes for gtk programs are described in ~/.gtkrc-2.0
file.

1. configure ~/.Xresources file and execute xrdb -merge
   .Xresources.

There are directory which contains system fonts settings /etc/fonts/conf.d/

#+begin_example
cd /etc/fonts/conf.d
sudo ln -s ../conf.avail/10-sub-pixel-rgb.conf .
#+end_example

*** Gtk
1. use lxappearence utility to configure ~/.gtkrc-2.0 file.
2. use gconf-editor to configure /desktop/gnome/interface/*-font-name

*** Qt

1. [[https://wiki.archlinux.org/index.php/Uniform_look_for_Qt_and_GTK_applications][Arch Wiki]]
  #+begin_example
  ~/.config/Trolltech.conf

  ...
  [Qt]
  style=GTK+
  ...
  #+end_example

  Or use qtconfig-qt4 utility from qt4-qtconfig package.

*** Firefox
Install addon Default Zoom Level. Then either in visual config or in
about:config change it's values.

*** Thunderbird

+ Install Themes and Fonts changer.
+ Use Zoom In (\C-=) and Zoom Out (\C--) to adjust reading pane zoom.

** Keyboard layout

There are many places which could control your keyboard layout. If you
don't use settings daemons then setxkbmap and xmodmap will work.

https://askubuntu.com/questions/451945/permanently-set-keyboard-layout-options-with-setxkbmap-in-gnome-unity

** Terminal and shell
*** Terminal
1. Install urxvt
2. Configure color theme
   https://wiki.mpich.org/mpich/index.php/Configure_xterm_Fonts_and_Colors_for_Your_Eyeball
3. Install addons
   http://funloop.org/post/2015-06-25-urxvt-plugins.html

   mkdir ~/.urxvt/ext
   git clone https://github.com/muennich/urxvt-perls --depth 1 ~/.urxvt/ext
   cd ~/.urxvt/ext
   wget wget https://raw.githubusercontent.com/majutsushi/urxvt-font-size/master/font-size

4. Configure addons in ~/.Xresources

5. Configure colors

   Bonus: [[https://github.com/chriskempson/base16][base16]] - set of 16-color schemes for text editors and
   terminal emulators.

   [[http://www.xcolors.net/][A lot of X themes]]

   [[https://wiki.archlinux.org/index.php/X_resources#Terminal_colors][Here]] is description of *color0..15 meaning.

6. tmux
   use https://github.com/tmux-plugins/tpm as plugins manager

*** Terminal color scheme

**** Base 16 themes:
Base 16 defines colors 00-07 as background gradations. The problem is that shell
commands expect colors 00-07 to be same as 08-0f. There are two ways to fix:
+ switch to some other theme like smyck
+ source corresponding shell script from base16 theme (it emphasized using face
  boldness instead of lighter colors).

Hint: how to choose exact theme?
1. tmux -2 new -s test # open many different terminal apps in tmux session
2. git clone --depth 1 https://github.com/chriskempson/base16-shell.git
   for i in ~/base16-xresources/base16-*.(dark|light).xresources; do
       echo "#include \"$i\"" >> ~/.Xresources
       xrdb ~/.Xresources; echo $i
       echo $i
       urxvt -name URxvt
   done
3. tmux attach -t test

   mkdir -p ~/.vim/colors
   cd ~/.vim/colors
   git clone git://github.com/chriskempson/base16-vim.git base16
   cp base16/colors/*.vim .

   echo "set background=dark" >> ~/.vimrc
   echo "colorscheme base16-default" >> ~/.vimrc

*** Shell
Most terminals (at least gnome-terminal, urxvt, and XTerm, for
example) that are started within a desktop environment such as Unity
will use the SHELL environment variable to select the shell when the
are launched.

**** Install fish shell
#+begin_example
echo "export SHELL=/usr/bin/fish" >> ~/.profile
chsh -s $(grep /fish$ /etc/shells | tail -1)
#+end_example

**** Or better install zsh

Easy way: use popular oh-my-zsh config

sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

**** Install fzf fuzzy matcher

(Note: install fzf after zsh or edit ~/.zshrc by hands)

git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install

** Clipboard
There are 3 types of text shared between X-applications: "primary
selection", "secondary selection" and "clipboard". Use
xclip -i -selection clipboard
xclip -o -selection clipboard
To copy/paste to/from clipboard
** Bind extra keys on mouse
xinput -list
xinput -test 10

Original keys meaning:
<left> <middle> <right> <s-up> <s-down> ? ? <forward> <backward>
Change <backward> to right in order to replace broken <right> button

xinput set-button-map "Logitech Unifying Device. Wireless PID:1028" 1 2 3 4 5 6 7 3 9
xinput --set-prop "Logitech Unifying Device. Wireless PID:1028" "Evdev Wheel Emulation" 1
xinput --set-prop "Logitech Unifying Device. Wireless PID:1028" "Evdev Wheel Emulation Button" 8

*** Tried tools which didn't help
 + xdotool - generates event only from virtual pointing device
 + easystroke - just didn't work

* General system config
** Locale
Edit /etc/default/locale. Set either "ru_RU.UTF-8" or "en_US.UTF-8" to
each field.

** Notifications
https://github.com/knopwob/dunst
Configuratin file ~/.config/dunst/dunstrc

** Hibernate
sudo -H gedit /etc/systemd/logind.conf
HandlePowerKey=hibernate
** autokey
Fix for exclusion window filter https://groups.google.com/forum/#!topic/autokey-users/ZYrQLPveh4g
Edit /usr/lib/python2.7/dist-packages/autokey/model.py and remove or from  def _should_trigger_window_title(self, windowInfo):  function
** TODO: check xautomation utility to replace autokey
* Applications
** DLNA media server
+ mediatomb

  You can find web-based interface address in logs
  #+begin_example
  cat /var/log/mediatomb.log | grep http://192 | tail -n 1 | cut -f 7 -d\
  #+end_example

+ minidlna

  * DLNA media server

** MTP
Checked several packages:
+ mtp-tools
+ mtpfs
+ jmtpfs

None of them detected my ASUS Phone.

** FTP
+ Install
  sudo apt-get install vsftpd

+ Enable anonymous users in /etc/vsftpd.conf
  anonymous_enable=Yes

+ Change home directory for anonymous user
  sudo usermod -d /mnt/ ftp

** Windows share
+ Install server and client
  sudo apt-get install samba smbclient

+ Configure
  sudo smbpasswd -a <user_name>
  sudo vi /etc/samba/smb.conf

  <    wins support = yes

  < [share]
  < path = /mnt/ex3
  < guest ok = yes
  < read only = yes

  Also configure home router to point just configured WINS server.

+ Test
  smbclient -L localhost
** DHCP server
Configured dhcp server to server on single interface. [[https://help.ubuntu.com/community/isc-dhcp-server#dhcp3-server_and_multiple_interfaces][Ubuntu Wiki]] contains good
description. In short:
+ sudo apt-get install dhcp3-server
+ configure static IP for interface via Network Manager applet;
+ list interface in /etc/default/isc-dhcp-server
+ define automatic IP ranger in /etc/dhcp/dhcpd.conf
+ logs are in /var/log/syslog and /var/log/upstart/isc-dhcp-server.log
+ sudo service isc-dhcp-server start
** Translators and dictionaries
*** dict

[[http://askubuntu.com/questions/380847/is-it-possible-to-translate-words-via-terminal][Stack Overflow post]]
#+begin_example
sudo apt-get install dictd
sudo apt-get install dict-freedict-eng-rus
#+end_example
** File manager
[[https://github.com/hut/ranger/wiki/Official-user-guide][Ranger]] is ineresting alternative to mc. It uses vim-like key bindings and single
panel (but allows tabs).
1. Initialize config files: ranger --copy-config=all
2. Edit ~/.config/ranger/rifle.conf and add emacs client as default editor:
   mime ^text,  label emacs = "emacsclient" -n "$@".
3. Implement ranger-cd function for your shell ([[https://gist.github.com/dbohdan/6257642][zsh version]])
** Misc
*** Documents
+ pdf :: xpdf is faster than evince so use it for large documents
+ djvu :: djview
*** Rust
Local installation without sudo ([[https://mpuppe.de/blog/2014/11/26/installing-rust-nightly-builds-into-your-home-directory/][from blogpost]]):
curl -s https://static.rust-lang.org/rustup.sh | sh -s -- --prefix=$HOME/.local --disable-sudo
*** Haskell
https://www.haskell.org/downloads/linux
** git server
*** connect using non-default ssh key

~/.ssh/config
Host tokio
    HostName xx.xx.xx.xx
    User ubuntu
    IdentityFile ~/.ssh/custom_key.pem

and then just ~ssh tokio~ or ~git clone tokio:repo~

*** configure server

http://planzero.org/blog/2012/10/24/hosting_an_admin-friendly_git_server_with_git-shell
** Emacs
*** Agenda via email
+ We send mail using sendmail
  http://tecadmin.net/send-email-from-gmail-smtp-via-linux-command/
+ Obtain password for app from google
  https://security.google.com/settings/security/apppasswords?pli=1
+ Configure cron task like this
  https://help.ubuntu.com/community/CronHowto
+ Use batch mode agenda
  http://orgmode.org/manual/Extracting-agenda-information.html

#+begin_example
emacs -batch --eval "(require 'org)"                             \
      -l ~/.spacemacs.d/user-config/literate-configs/org-mode.el \
      --eval '(org-batch-agenda "a")' |                          \
                                     \
sendemail -f "kevroletin@gmail.com"  \
          -u "Dayly agenda"          \
          -t "kevroletin@gmail.com"  \
          -s "smtp.gmail.com:587"    \
          -o tls=yes                 \
          -xu "kevroletin@gmail.com" \
          -xp "password_here"
#+end_exaple
