#!/bin/bash

/home/behemoth/bin/switch-dark-theme &

systemctl --user start voxtype

# xue-hanzi anki cards backend
cd ~/Scratch/js/hanzi-writer/character-server && cargo run &

# proxy autoconfig
busybox httpd -v -f -p 8910 -c /home/behemoth/Scratch/desktop/proxy_config/.httpd.conf -h /home/behemoth/Scratch/desktop/proxy_config &

# at-spi consumes cpu https://bbs.archlinux.org/viewtopic.php?id=237697
export NO_AT_BRIDGE=1

#rm -f ~/.xmonad/xmonad.state
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

# work around problem with java applications
export _JAVA_AWT_WM_NONREPARENTING=1

# gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh

# separate layout for each window
kbdd

/home/behemoth/bin/xremap --watch=device,config /home/behemoth/.xremap.yml &

xsetwacom --set "$(xsetwacom --list devices | grep STYLUS | awk '{print $9}')" Rotate half

# configure cursor
xsetroot -cursor_name left_ptr

# /usr/bin/xscreensaver &
# xset dpms 0 0 0

if pgrep "redshift" > /dev/null
then
    pkill redshift
fi
redshift &

xrandr --output DP-3 --off --output DP-1 --off --output eDP-1 --mode 1920x1080 --primary --pos 0x0 --rotate normal --output DP-2 --off

# Set the background image/color
feh --bg-scale ~/ra.jpg

xrdb -merge ~/.Xresources

trayer --edge top --align right --SetDockType true --SetPartialStrut true \
 --expand true --width 10 --transparent true --tint 0x191970 --height 18 &

if [ -x /usr/bin/nm-applet ] ; then
   nm-applet --sm-disable &
fi

xmonad
